#!/usr/bin/env python3
"""Rebuild the conservative Bulma subset used by this page.

Install tinycss2, then run: python3 scripts/build_project_css.py
The full upstream stylesheet remains available in static/css/bulma.min.css.
Rules requiring classes absent from this page are removed. All element rules,
negative selectors, responsive rules, and native hover/focus states are kept.
Regenerate the stylesheet whenever adding Bulma classes to index.html.
"""
from html.parser import HTMLParser
from pathlib import Path

import tinycss2

ROOT = Path(__file__).resolve().parents[1]


class PageClasses(HTMLParser):
    def __init__(self):
        super().__init__()
        self.classes = set()

    def handle_starttag(self, tag, attrs):
        for key, value in attrs:
            if key == 'class' and value:
                self.classes.update(value.split())


page = PageClasses()
page.feed((ROOT / 'index.html').read_text())
# Classes toggled by index.js; keep their framework states as well.
classes = page.classes | {'is-active', 'copied', 'visible', 'show'}


def required_classes(tokens):
    required = set()
    for i, token in enumerate(tokens):
        if token.type == 'literal' and token.value == '.':
            if i + 1 < len(tokens) and tokens[i + 1].type == 'ident':
                required.add(tokens[i + 1].value)
        elif token.type == 'function' and token.lower_name != 'not':
            required.update(required_classes(token.arguments))
    return required


def split_selectors(tokens):
    selector = []
    for token in tokens:
        if token.type == 'literal' and token.value == ',':
            yield selector
            selector = []
        else:
            selector.append(token)
    yield selector


def subset(rules):
    output = []
    for rule in rules:
        if rule.type == 'qualified-rule':
            selectors = [tinycss2.serialize(s).strip() for s in split_selectors(rule.prelude)
                         if required_classes(s) <= classes]
            if selectors:
                output.append(','.join(selectors) + '{' + tinycss2.serialize(rule.content) + '}')
        elif rule.type == 'at-rule' and rule.lower_at_keyword in {'media', 'supports'}:
            body = subset(tinycss2.parse_rule_list(rule.content, skip_whitespace=True))
            if body:
                output.append('@' + rule.at_keyword + ' ' + tinycss2.serialize(rule.prelude).strip()
                              + '{' + body + '}')
        elif rule.type == 'comment':
            if rule.value.startswith('!'):
                output.append(tinycss2.serialize([rule]))
        elif rule.type not in {'whitespace', 'error'}:
            output.append(tinycss2.serialize([rule]))
        elif rule.type == 'error':
            raise ValueError(rule.message)
    return ''.join(output)


if __name__ == '__main__':
    source = ROOT / 'static/css/bulma.min.css'
    target = ROOT / 'static/css/bulma-project.min.css'
    css = subset(tinycss2.parse_stylesheet(source.read_text(), skip_whitespace=True))
    target.write_text('/* Generated by scripts/build_project_css.py; regenerate when page classes change. */\n'
                      + css + '\n')
    print(f'Bulma: {source.stat().st_size:,} -> {target.stat().st_size:,} bytes')
